title: "DefCodex Blog"
description: "DefCodex Blog shares coding tutorials, tips, and insights for developers."
url: "https://defcodex.github.io"
baseurl: "/defcodex"
lang: "en"
theme: jekyll-theme-modernist
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemut
github_username: "defcodex"
