title: "DefCodex Blog"
description: "DefCodex Blog shares coding tutorials, tips, and insights for developers."
url: "https://defcodex.github.io"
 baseurl: ""
lang: "en"
theme: jekyll-theme-cayman
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
author:
  name: "DefCodex"
