title: "DefCodex Blog"
description: "DefCodex Blog shares coding tutorials, tips and insights for developers."
url: "https://defcodex.github.io"
baseurl: ""
lang: "en"
timezone: "America/New_York"

# Use the official Cayman GitHub Pages theme as a base.
remote_theme: pages-themes/cayman@v0.2.0

markdown: kramdown
highlighter: rouge

# Pretty permalinks for posts (no categories to avoid empty segments)
permalink: /:year/:month/:day/:title/

# Plugins supported by GitHub Pages
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Feed options (keeps default path /feed.xml)
feed:
  path: feed.xml

author:
  name: "DefCodex"

# Ensure layouts are applied even when a page/post forgets front matter values
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "DefCodex"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

# Exclude dev-only files from the site output
exclude:
  - README.md
  - node_modules
  - Gemfile
  - Gemfile.lock

# Counter settings (used by CountAPI in templates)
counter:
  namespace: "defcodex.github.io"   # change here if you move to a custom domain
  site_total_key: "site-total"
