title: "DefCodex Blog"
description: "DefCodex Blog shares coding tutorials, tips and insights for developers."
url: "https://defcodex.github.io"
baseurl: ""
lang: "en"

# Use the official Cayman GitHub Pages theme as a base.
remote_theme: pages-themes/cayman@v0.2.0

markdown: kramdown
highlighter: rouge
permalink: /:categories/:year/:month/:day/:title/

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

author:
  name: "DefCodex"

# Ensure posts and pages always have a layout applied even if front matter is missing.
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "DefCodex"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

# Optional: exclude dev-only files from the build
exclude:
  - README.md
  - node_modules
