title: "DefCodex Blog"
description: "DefCodex Blog shares coding tutorials, tips, and insights for developers."
url: "https://defcodex.github.io"
baseurl: "/defcodex"
lang: "en"
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
author:
  name: "DefCodex"
  url: "https://defcodex.github.io/defcodex"
github_username: "defcodex"
